### ISSUE TITLE
Possible to initial developement with offline data?

### ISSUE THREAD

**Issue by gsivaprabu** [openbmc/webui-vue#1]
This one is not an issue just a suggestion possible to use offline data (api responses in odata format in local) not getting live data from server. (For Developement purpose)?

[OpenBMC REST cheat sheet](https://github.com/openbmc/docs/blob/master/REST-cheatsheet.md#establish-rest-connection-session)

![image](https://user-images.githubusercontent.com/2444608/75094309-f10cb100-55af-11ea-80a7-0d519c4cfc9e.png)

**Comment by derick-montague** [comment]
Much of this will be migrated from the REST API to Redfish. Also, this doesn't seem like a WebUI issue and may be better discussed in https://github.com/openbmc/bmcweb possibly. @gtmills can you verify that for me?

**Comment by gsivaprabu** [comment]
Thanks @derick-montague

**Comment by derick-montague** [comment]
Thank you for your feedback @gsivaprabu. Unless there is an objection, I am going to close this issue.
