### ISSUE TITLE
failed to build webui with v2.14.0

### ISSUE THREAD

**Issue by laoshaw** [openbmc/webui-vue#103]
**Describe the bug** A clear and concise description of what the bug is.

failed to build under v2.14.0 release, also reported here: https://github.com/openbmc/openbmc/issues/3929

**To Reproduce** Steps to reproduce the behavior:

. setup romulus
time bitbake obmc-phosphor-image

```
| npm http fetch GET 200 https://registry.npmjs.org/@vue%2fcli-plugin-eslint 116ms (cache miss)
| npm http fetch GET 200 https://registry.npmjs.org/eslint 29ms (cache hit)
| npm ERR! code ERESOLVE
| npm ERR! ERESOLVE unable to resolve dependency tree
| npm ERR!
| npm ERR! While resolving: webui-vue@0.1.0
| npm ERR! Found: eslint@7.22.0
| npm ERR! node_modules/eslint
| npm ERR!   dev eslint@"7.22.0" from the root project
| npm ERR!
| npm ERR! Could not resolve dependency:
| npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.12
| npm ERR! node_modules/@vue/cli-plugin-eslint
| npm ERR!   dev @vue/cli-plugin-eslint@"4.5.12" from the root project
| npm ERR!
| npm ERR! Fix the upstream dependency conflict, or retry
| npm ERR! this command with --force or --legacy-peer-deps
| npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Initial checkup, the error is quite obvious, webui's package-lock.json installs eslint 7.22.0 but one of its package, @vue/cli-plugin-eslint@"4.5.12", mandates eslint to be eslint@">= 1.6.0 < 7.0.0", thus the conflict and failed the build.

**Expected behavior** A clear and concise description of what you expected to
happen.

should be built without errors

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] ubuntu 22.04
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] newest

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by sivaprabug** [comment]
I also facing the same issue @laoshaw 

For a workaround change, the  [@vue/cli-plugin-eslint](https://www.npmjs.com/package/@vue/cli-plugin-eslint) version **4.5.12 to 5.0.8**

![image](https://github.com/openbmc/openbmc/assets/2444608/b0dd50f2-1314-42af-b607-24620e52f7aa)

**Comment by gtmills** [comment]
We are now using 5.0.8 
https://github.com/openbmc/webui-vue/blob/511650a90260e0922bfeb1091b4babc597d36af6/package.json#L40

Closing. Please reopen if still an issue.
