### ISSUE TITLE
Addition and removal of some DIMM Inventory Data in WebUI

### ISSUE THREAD

**Issue by Rashmi-RV** [openbmc/webui-vue#107]
Below DIMM Inventory Data to be added to WebUI. 

1.Manufacturer
2.Error Correction
3.Rank Count 

Below DIMM inventory data to be removed from WebUI as they are empty:

1.Spare part number,
2. Enabled,
3.Model

These data are already in place via redfish.

![image](https://github.com/openbmc/webui-vue/assets/50362574/8d2fd72f-566b-4b53-a2b7-b98c53a38d79)

**Comment by thangqn-ampere** [comment]
Should we show Health to a value different than OK? Let sau we have 16 DIMM slots but only 1 or 2 DIMMs plugged. Can’t know what are available unless expanding all rows

**Comment by jmbills** [comment]
I pushed a change to add the three requested fields: https://gerrit.openbmc.org/c/openbmc/webui-vue/+/64228.

I don't think we can remove fields until we get approval from the community.  If we want to remove them, I'd suggest starting a thread in the mailing list proposing to remove them and asking if anyone uses them.

**Comment by gtmills** [comment]
> 1.Spare part number,
> 2. Enabled,
> 3.Model

We use these fields. 
For SparePartNumber, it was left out of the API if not supported. 
If it is not there, can the GUI leave it off?
https://github.com/openbmc/bmcweb/blob/01a89a1f05f960fa91b7e90a641faa3850e3c3ff/redfish-core/lib/processor.hpp#L457

Some way with Enabled to determine if not supported?

Model is a pretty common property and part of that Asset interface; if you really don't think it should show on the GUI, you need to drive something in the backend similar to SparePartNumber 
https://github.com/openbmc/bmcweb/blob/01a89a1f05f960fa91b7e90a641faa3850e3c3ff/redfish-core/lib/processor.hpp#L430

**Comment by kirankumarb07** [comment]
@Rashmi-RV @jmbills 

This issue related following PR does not contain code of any removal of properties as mentioned in this git task. Its contradicting  between git task and PR code changes. 

https://gerrit.openbmc.org/c/openbmc/webui-vue/+/64228

So please help to update GIT task title, description as per PR code changes.

Regards,
Kiran.

**Comment by gtmills** [comment]
I am good with https://gerrit.openbmc.org/c/openbmc/webui-vue/+/64228 
Any removal / leaving off fields can be handled separately

**Comment by kirankumarb07** [comment]
@Rashmi-RV @gtmills please close this issue as PR has been merged.

**Comment by jmbills** [comment]
New fields have been added based on this issue.  Removed fields can be discussed in a new issue.
