### ISSUE TITLE
Health icon shows ok while loading

### ISSUE THREAD

**Issue by matijas-1987** [openbmc/webui-vue#11]
**Describe the bug**
While web UI is loading it is showing controls as "OK" state instead of undetermined which might be confusing.

**To Reproduce**
1. Go to home page
2. See header. While loading health is green, after loading is red.

**Expected behavior**
If page is loading the health icon should be undetermined.

**Screenshots**

while loading
![GetImageAttachment](https://user-images.githubusercontent.com/66257423/87668262-1ae78f80-c76c-11ea-8900-1372f5ea4ae1.png) 
 after loading
![GetImageAttachment (1)](https://user-images.githubusercontent.com/66257423/87668272-1d49e980-c76c-11ea-894b-0dd7dd194c7b.png)

**Comment by derick-montague** [comment]
Thank you @matijas-1987!

**Comment by lukkep** [comment]
@derick-montague we have found few UI bugs that @matijas-1987 reported. Could you please assign them to @matijas-1987 ? :)
He will tackle those like a pro. ;) If you have any concerns - we can discuss those within today's meeting.

**Comment by derick-montague** [comment]
Completed in https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34879
