### ISSUE TITLE
User Privilege Route management prevents AD/LDAP user login

### ISSUE THREAD

**Issue by brian-arrington-dell** [openbmc/webui-vue#110]
The privilege route management addition from https://github.com/openbmc/webui-vue/commit/aeb19816e67f6d3ffb1b37c95d813a25b8be1d7b needs to be removed as it is preventing AD/LDAP users from logging in.  This is due to the privileges being retrieved from the AccountService/Account/<accountId> api call which does not retrieve AD/LDAP users and returns a 404 (expected behavior).  As a result no routes are added for AD/LDAP users and they remain at the login page.  The [redfish spec](https://github.com/DMTF/Redfish-Publications/blob/main/csdl/ManagerAccount_v1.xml#L47) does not support AD/LDAP user management from the Account Service.

**Comment by awan119** [comment]
Is there any update here?

I have created ldap server but couldn't log in with ldap account properly. It seems that privilege roue management makes this happen like @brian-arrington-dell said.

**Comment by gtmills** [comment]
Does https://gerrit.openbmc.org/c/openbmc/webui-vue/+/70758 fix this?

**Comment by awan119** [comment]
Hi,

Yes, this patch fixes the problem.
Thank you.

**Comment by gtmills** [comment]
https://gerrit.openbmc.org/c/openbmc/webui-vue/+/70758 has merged. Closing.
