### ISSUE TITLE
Boundary testing - long and short user input

### ISSUE THREAD

**Issue by brian-arrington-dell** [openbmc/webui-vue#111]
User inputs for long names cause overflow issues in the UI.  

Examples:  
- Host Name with 64 characters overflow 
- LDAP Role group names

Additionally, LDAP role groups can be created using only whitespace characters.

![host](https://github.com/openbmc/webui-vue/assets/149721816/828ac028-7014-4d57-aa79-3410fa6bad42)
![role](https://github.com/openbmc/webui-vue/assets/149721816/9c5b9b3e-6cdf-4bd5-a1aa-4fdbee1f2bc1)

**Comment by FarahRasheed1** [comment]
Code Review link to the bug about the network hostname overflowing: https://gerrit.openbmc.org/c/openbmc/webui-vue/+/72458

Pre-bugfix screenshot: 
![PreFixBenchTestScreenshotNetworkSettingsHostName](https://github.com/openbmc/webui-vue/assets/169199595/814dba44-88bc-4fd5-ad86-0b49f710d9cd)

Post-bugfix screenshot:
![PostFixBenchTestScreenshotNetworkSettingsHostName](https://github.com/openbmc/webui-vue/assets/169199595/23ee987c-9f84-4b52-a663-8b7181eed409)

**Comment by FarahRasheed1** [comment]
Code review to the bug about edit role group overflowing issue: https://gerrit.openbmc.org/c/openbmc/webui-vue/+/72459

Bench Test Results:

Before bug fix:

![PreFixBenchTestResultsEditRoleGroup](https://github.com/openbmc/webui-vue/assets/169199595/63e60e66-e30c-4783-960c-6b0ef9004664)

After bug fix:

![PostFixBenchTestResultsEditRoleGroup](https://github.com/openbmc/webui-vue/assets/169199595/efca1b9b-6dd4-4988-8bda-bb9f3f2ee0df)

**Comment by FarahRasheed1** [comment]
Gerrit code review link for the issue related to whitespace in role group names: https://gerrit.openbmc.org/c/openbmc/webui-vue/+/72463

Bench test results:

Pre-fix bench test results:

Post fix bench test results:

Trying to add an empty role group name:

![PostFixBenchTestOnlyWhitespace](https://github.com/openbmc/webui-vue/assets/169199595/768fab48-02c4-4c95-9d86-1ac2a9c15d56)

Adding a role group name with whitespace:

![PostFixBenchTestTrimWhitespace1](https://github.com/openbmc/webui-vue/assets/169199595/23313389-7d67-44fa-9889-73fedc32130e)

The whitespace is trimmed before submit:

![PostFixBenchTestTrimWhitespace2](https://github.com/openbmc/webui-vue/assets/169199595/f286351c-11ba-4911-9745-3fc2683f16c0)
