### ISSUE TITLE
what is web timeout time?

### ISSUE THREAD

**Issue by jack206** [openbmc/webui-vue#112]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by jack206** [comment]
Could someone please tell me what the default timeout time of the web is and how to change it?

**Comment by sivaprabug** [comment]
The default web timeout is 30 minutes. You change the timeout value under the policy page.

FYI : 


https://github.com/openbmc/webui-vue/commit/2dabfc1bb488f84ec00f19a51aba144b7f71e45d

Via Redfish : 

```shell
/redfish/v1/SessionService
```
**Payload:**

```json
{"SessionTimeout": 1800}
```

**Comment by gtmills** [comment]
Is this still a problem or can this be closed?

**Comment by gtmills** [comment]
No response. Please reopen if still an issue. Thanks!
