### ISSUE TITLE
Unable to log into the BMC WebUI

### ISSUE THREAD

**Issue by huyle-anh** [openbmc/webui-vue#116]
**Describe the bug:** 

With bmcweb `743eb1c0` and webui-vue `01492c3` unable to log into the BMC WebUI. It seems like this has been happening lately, before that, didn't see this happening.

**To Reproduce**:

1. Go to BMC WebUI by entering https://BMC_IP and then typing with `root/0penBMC`
2. Click `Login` Button
3. Step "2", can't sign in to BMC WebUI.

**Expected behavior**
Log in to the BMC WebUI successful.

**Screenshots**.

<img width="614" alt="Screenshot 2024-05-08 at 23 51 50" src="https://github.com/openbmc/webui-vue/assets/7159126/486f9a30-c331-4699-8e73-7de5824e5cb4">

**Desktop (please complete the following information):**

- Mac OS Ventura 13.6.5
- Browser: Chrome Version 124.0.6367.156

**Comment by zevweiss** [comment]
See https://github.com/openbmc/bmcweb/issues/273, which was initially reported for a different problem but has stumbled onto this one as well.

**Comment by edtanous** [comment]
Can you capture the network console log from your browser when this failure happens?  Are there any requests that have failed?  In the past I've seen a case where the webui requestst the /redfish/v1/AccountService/Accounts/null user (which obviously doesn't exist) then doesn't handle the error well.

**Comment by edtanous** [comment]
nevermind about the log, I think I found it.  Can you please try:
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/71309

**Comment by huyle-anh** [comment]
> See [openbmc/bmcweb#273](https://github.com/openbmc/bmcweb/issues/273), which was initially reported for a different problem but has stumbled onto this one as well.

I'm not sure the same issue, but I've also encountered before with errors when end `Session timeout` browser refresh BMC WebUI will doesn't reload to the login page, only when deleting Cookies Value "XSRF-TOKEN" the Login page is reloaded. Currently, fixed by commit: [https://gerrit.openbmc.org/c/openbmc/bmcweb/+/70292/10](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/70292/10)

> nevermind about the log, I think I found it. Can you please try: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/71309

Thanks, @edtanous, applied the patch and checked BMC WebUI login successfully.
--Regards,

**Comment by huyle-anh** [comment]
This issue fixed by https://gerrit.openbmc.org/c/openbmc/bmcweb/+/71309, so I close this bug.

--
