### ISSUE TITLE
No span/margin between table and buttons

### ISSUE THREAD

**Issue by matijas-1987** [openbmc/webui-vue#12]
**Describe the bug**
Access Control - Local User management 
No span/margin between table and buttons

![no-margin](https://user-images.githubusercontent.com/66257423/87779574-47171500-c82d-11ea-9b47-98e836a71f3b.png)

**Comment by derick-montague** [comment]
@yoshiemuranaka @matijas-1987 @ben-bacon - This has been discussed a few times. This is as designed, but I think we can open up that discussion to look into any issues being experienced with the layout.

**Comment by lukkep** [comment]
Thanks for comment @derick-montague. For me, it would be OK if button next to it ("Account policy settings") would have similar styling. Now it looks a little bit odd IMHO. 😉

**Comment by derick-montague** [comment]
Will add this to the next GUI Design Work group.

**Comment by yoshiemuranaka** [comment]
For reference, although we're not using the Carbon design system, we've followed a similar pattern for some of table layout patterns.
https://www.carbondesignsystem.com/components/data-table/usage/#formatting

The flushed buttons was an intentional design choice

**Comment by matijas-1987** [comment]
We can close this issue. It's ok for us. @yoshiemuranaka, thank you for your explanation.

**Comment by derick-montague** [comment]
Thank you, @matijas-1987
