### ISSUE TITLE
question about dbus call in webui-vue

### ISSUE THREAD

**Issue by seanzhangseu** [openbmc/webui-vue#120]
Hi,

Does any know if additional configuration needed for dbus request in bmc?

    async getTpmPolicy({ commit }) {
      // TODO: switch to Redfish when available
      return await api
        .get('/xyz/openbmc_project/control/host0/TPMEnable')
        .then(({ data: { data: { TPMEnable } } }) =>
          commit('setTpmPolicy', TPMEnable)
        )
        .catch((error) => console.log(error));
    },

![image (1)](https://github.com/openbmc/webui-vue/assets/89561987/4c281069-9dc2-472d-96ea-2a21026d95e5)

Thanks.

**Comment by fishermess** [comment]
You just need to config bmcweb url。后端接口都没有搞毛线啊，叫后端给你配一个dbus接口。
