### ISSUE TITLE
Web application cannot follow the normal flow to establish a session

### ISSUE THREAD

**Issue by Betty0105** [openbmc/webui-vue#127]
When the web deletes a session, the browser automatically displays the login prompt ("This site is asking you to sign in"). When using this login prompt to sign in, the web application cannot follow the normal flow to establish a session. How can this issue be resolved? Thank you !
![image](https://github.com/user-attachments/assets/43ff55d9-177e-48f9-ab11-b336ecbaa036)

**Comment by williamspatrick** [comment]
"the normal flow to establish a session"... can you elaborate?

**Comment by Betty0105** [comment]
When a user logs in through the login page, the /login API defined in bmcweb is executed. In the /login API, the generateUserSession function is used to create a session. The Sessions page on the web will display the session information.

![image](https://github.com/user-attachments/assets/df89eae6-6f90-4840-9086-04805cff0b68)

However, if the user logs in via the browser's pop-up login window, even though login is successful, it will not execute the /login API defined in bmcweb. Thus, the Sessions page on the web will not display that session information.

**Comment by Betty0105** [comment]
This issue has been resolved, thank you.
