### ISSUE TITLE
Naming convention in menu

### ISSUE THREAD

**Issue by matijas-1987** [openbmc/webui-vue#13]
**Describe the bug**
we should be consistent with naming options. Some options starts all words with uppercase some not.

![menu](https://user-images.githubusercontent.com/66257423/87779715-8c3b4700-c82d-11ea-843c-5e1311dd881b.png)

**Comment by derick-montague** [comment]
Convention is lower case for second word unless it's something like `LED`

**Comment by matijas-1987** [comment]
@derick-montague , please assign to me
