### ISSUE TITLE
Weird underscore

### ISSUE THREAD

**Issue by matijas-1987** [openbmc/webui-vue#14]
**Describe the bug**
Network settings - "System" option have weird underscore. 

![underscore](https://user-images.githubusercontent.com/66257423/87779967-023fae00-c82e-11ea-9609-69563c5a27a8.png)

**Comment by derick-montague** [comment]
Is the only place you are seeing this? Can. you share some of this info?

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Comment by lukkep** [comment]
Hmm... Currently I cannot reproduce this issue. 
Let's close it.  😃 

It was:
- Windows 10,
- Edge.

**Comment by derick-montague** [comment]
Can't reproduce
