### ISSUE TITLE
Event logs table - option not determine should have text

### ISSUE THREAD

**Issue by matijas-1987** [openbmc/webui-vue#16]
**Describe the bug**
Event logs table - it would be nice to have consistent cells, if option is not deremine there is no text.

![not-determine](https://user-images.githubusercontent.com/66257423/87780446-09b38700-c82f-11ea-9efd-c6640e40e4a3.png)

**Comment by derick-montague** [comment]
There seems to be some issues here. This seems like a custom build as the icons are not the same and the colors are off. Can you share more about this state? @matijas-1987

**Comment by matijas-1987** [comment]
Part of json, I see that severity is empty: 
   {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/1595341436",
      "@odata.type": "#LogEntry.v1_4_0.LogEntry",
      "Created": "2020-07-21T14:23:56+00:00",
      "EntryType": "Event",
      "Id": "1595341436",
      "Message": "Power Unit Redundancy regained.",
      "MessageArgs": [],
      "MessageId": "OpenBMC.0.1.PowerUnitRedundancyRegained",
      "Name": "System Event Log Entry",
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/1595341609",
      "@odata.type": "#LogEntry.v1_4_0.LogEntry",
      "Created": "2020-07-21T14:26:49+00:00",
      "EntryType": "Event",
      "Id": "1595341609",
      "Message": "",
      "MessageArgs": [
        "2"
      ],
      "MessageId": "OpenBMC.0.1.BeepCode",
      "Name": "System Event Log Entry",
      **"Severity": ""**
    },

**Comment by derick-montague** [comment]
Now I understand! This seems like a bug with the `status-icon` component. FYI @yoshiemuranaka

**Comment by matijas-1987** [comment]
@derick-montague , @yoshiemuranaka, please let me know if severity is empty I shouldn't show icon or  show default status (e.g Not  determined)

**Comment by derick-montague** [comment]
@matijas-1987 What does it mean if there isn't a value for the severity property? Is this a common use case?

I would suggest no value and no icon if so. @yoshiemuranaka?

**Comment by yoshiemuranaka** [comment]
Yes, let's move forward with hiding the status icon if there is no value defined from backend

**Comment by matijas-1987** [comment]
@derick-montague, assign to me :)
