### ISSUE TITLE
Sensors - not needed scroll is displayed 

### ISSUE THREAD

**Issue by matijas-1987** [openbmc/webui-vue#17]
**Describe the bug**
Sensors - not needed scroll is displayed (you can barely use it).

![sensors](https://user-images.githubusercontent.com/66257423/87780532-34054480-c82f-11ea-8085-a21f653bb4f6.png)

**Comment by derick-montague** [comment]
This is an issue that is part of the responsive class and out of the box Bootstrap. I definitely agree. We need to look into the breakpoints that the responsive property is being set.

**Comment by dixsie** [comment]
I believe this may have been addressed in one of @SurenNeware commits in Gerrit
