### ISSUE TITLE
File input should have english language text

### ISSUE THREAD

**Issue by matijas-1987** [openbmc/webui-vue#20]
**Describe the bug**
Access Control->SSL Certificates -> Add new certificate
Wrong language text in file input. Probably language is from browser.

**Expected behavior**
English language in file input

![file-input](https://user-images.githubusercontent.com/66257423/87782966-d32c3b00-c833-11ea-8f1c-d6b758fe9cf7.png)

**Comment by lukkep** [comment]
Language use on button should match language in browser. 
This might be tricky as it looks that buttons in file upload control use standard, system button.

@matijas-1987 you will need probably to make new control using same styles as "Cancel"/"Add" buttons. :)

**Comment by matijas-1987** [comment]
Unfortunately, the change of text in default file input is impossible. So, I decided to use another version of bootstrap control which override standard file input.  

![image](https://user-images.githubusercontent.com/66257423/88268629-09096d80-ccd3-11ea-9cab-2de331865b44.png)
