### ISSUE TITLE
Plan for Firmware web page(s) ?

### ISSUE THREAD

**Issue by frsauvage** [openbmc/webui-vue#26]
Hi,
Do you have any date about firmware web page(s) ?
Is it a priority ? Could we expect it far before June 30 2021 at least ?

I apologize if these questions were already answered somewhere ?

Best regards,
Francine

**Comment by derick-montague** [comment]
Thank you for your question, @frsauvage! It was planned for end of June 2020 and was pushed to the end of July 2020. The single firmware image design is being developed, both front-end and backend concurrently. If the two file upload (separate update for host and BMC), we have a design we can share, but it is a help wanted item #9.

**Comment by frsauvage** [comment]
Thank a lot @derick-montague, so excited about it !
Best regards,
Francine

**Comment by frsauvage** [comment]
Hi, it's end of July and I can't find Update VueJS View, no? did I miss something ?
Any news ?
Best regards
Francine

**Comment by gtmills** [comment]
Hi @frsauvage,

Single file code update merged here: https://github.com/openbmc/webui-vue/commit/92a0a4ac1f25271c1861d7c97a0d8344dd578905

There is still work needed to do 2 file code update (a separate BMC and System code update): https://github.com/openbmc/webui-vue/issues/9

IBM has moved 2 of their systems over to using webui-vue 
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/35445

**Comment by derick-montague** [comment]
We are also working on two-file to meet parity with the phosphor-webui GUI. Review in progress now. #9

**Comment by gtmills** [comment]
Closing, please reopen if you think there is still something left here.
