### ISSUE TITLE
CSRF allow list

### ISSUE THREAD

**Issue by gtmills** [openbmc/webui-vue#29]
We had this security feature in phosphor-webui

**Comment by derick-montague** [comment]
I am not sure what is needed on the client-side for this.

**Comment by derick-montague** [comment]
[Conversation in discord](https://discord.com/channels/775381525260664832/776550056391606352/780834368498302976)

Derick Montague:
> I was looking a bit into the CSRF allow list. I believe what you are referring to is the xsrfTrustedOrigins and/or the xsrfWhitelistedOrigins that are part of AngularJS's $http service. Is that right?  If so, I am not quite sure how they are being used. https://docs.angularjs.org/api/ng/provider/$httpProvider#xsrfWhitelistedOrigins
`@edtanous` was that your expectation when you brought this to our attention?

Ed Tanuous:
> Yep.  Considering the CSRF token is considered a secret, the webui needs to only send it if the hostname matches self.  I don't think you need to implement a real ignore list, because the webui won't be talking to any other servers directly.

**Comment by dixsie** [comment]
The current xsrf cookie implementation in webui-vue protects against CSRF attacks. 

For added security and consistency across different browsers we should add the set-cookie sameSite attribute to strict on the backend. If strict is set “the cookie will only be sent if the site for the cookie matches the site currently shown in the browser’s URL” https://web.dev/samesite-cookies-explained/#explicitly-state-cookie-usage-with-the-samesite-attribute 
Adding this attribute was tested with an image and no breaking changes were observed.

**Comment by derick-montague** [comment]
> The current xsrf cookie implementation in webui-vue protects against CSRF attacks.
> 
> For added security and consistency across different browsers we should add the set-cookie sameSite attribute to strict on the backend. If strict is set “the cookie will only be sent if the site for the cookie matches the site currently shown in the browser’s URL” https://web.dev/samesite-cookies-explained/#explicitly-state-cookie-usage-with-the-samesite-attribute
> Adding this attribute was tested with an image and no breaking changes were observed.

@gtmills added this change as a test and this change will be need to be implemented in BMCWeb

**Comment by derick-montague** [comment]
We expect this to be resolved by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41383. 

If no one has a concern, I will be closing this story on Monday, 3/22/21.
