### ISSUE TITLE
Date and Time Settings

### ISSUE THREAD

**Issue by derick-montague** [openbmc/webui-vue#3]
## Use Case
As a BMC Administrator I need to be able to update time that may have drifted on a system that does not use an NTP server to sync the clock with other systems over the internet without having to shutdown the host and disrupt service.

## Invision Prototype Guidance
The Invision prototypes have hot spots allowing the reviewer to step through the workflow. To navigate a prototype, you can:

1. Click on the page and the hotspots will be revealed in blue
1. Use the arrow-right and arrow-left keys on your keyboard

## Design Review Workflow
1. Each design iteration will have a comment section
1. The section will include:
    - A title with the iteration number
    - Any description or specific feedback the designer is requesting
    - Screenshots of the workflow
1. Based on community and user feedback, we create a comment for the new iteration and repeat these steps

**Comment by derick-montague** [comment]
## Current proposal
[Invision prototype](https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319420720_01-Date-And-Time-Settings-02)

### Screen shots
![image](https://user-images.githubusercontent.com/1183515/76430205-0b9ba400-637e-11ea-96d4-9b19ac19ba14.png)

![image](https://user-images.githubusercontent.com/1183515/76430246-18b89300-637e-11ea-971f-83a0b4b944b1.png)

![image](https://user-images.githubusercontent.com/1183515/76430412-52899980-637e-11ea-9528-8311262e69fc.png)

![image](https://user-images.githubusercontent.com/1183515/76430445-57e6e400-637e-11ea-9317-c9cf0317dda4.png)

![image](https://user-images.githubusercontent.com/1183515/76430466-5cab9800-637e-11ea-9647-e6f4b06e4df2.png)

![image](https://user-images.githubusercontent.com/1183515/76430490-61704c00-637e-11ea-9c4a-9697d3a93833.png)

![image](https://user-images.githubusercontent.com/1183515/76430509-66350000-637e-11ea-9b71-be40d39c37fd.png)

**Comment by derick-montague** [comment]
x86 systems do not offer a manual date and time setting. The date and time can either be sync'd with an NTP server or it is set by the hosts Real-time clock (RTC). The goal of this design is to be able to have all options supported upstream with with the ability to toggle the functionality based on the build or some type of flag.

**Comment by williamspatrick** [comment]
How do you plan on the time-zone being utilized within the BMC?  I think we currently expect the BMC to internally use the UTC timezone only for all logging, etc.  Is this something that is only applicable to users through the WebUI (are we going to translate all timestamps for them?)?

**Comment by williamspatrick** [comment]
> x86 systems do not offer a manual date and time setting.

I don't think this is an architectural requirement, but simply how most x86 systems have currently implemented things from a hardware perspective.  The IPMI method that Power is using to get the time up to the host firmware could also be implemented on x86, but just isn't in most implementations.

It is still useful to be able to set the time on the BMC though, so that logs "make sense".  That time just might not be 100% in sync with the Host's view of time (and could potentially be overwritten by the Host on next boot).

I'm not sure there is a strong reason to disable this screen on current x86 systems.

**Comment by derick-montague** [comment]
> How do you plan on the time-zone being utilized within the BMC? I think we currently expect the BMC to internally use the UTC timezone only for all logging, etc. Is this something that is only applicable to users through the WebUI (are we going to translate all timestamps for them?)?

The timezone is only a convenience for users to avoid time conversion. Avoiding the need to figure out the offset  was a consistent comment in user testing. The BMC will only use that dropdown to do the conversion for the user and save as UTC time.

**Comment by joseph-reynolds** [comment]
I didn't see anything on the interface that talks about correcting time drift.  I understand the operating system does that under the covers.

I understand the change here is to add the "manual" setting.  Will that change the platform clock immediately, or will it drift toward the new setting?

**Comment by derick-montague** [comment]
> I didn't see anything on the interface that talks about correcting time drift. I understand the operating system does that under the covers.

I'm not sure that is true, but you would know better. Our users have stated that they have to update the clock because of the drift. 

> I understand the change here is to add the "manual" setting. Will that change the platform clock immediately, or will it drift toward the new setting?

We already have a manual setting. This is reviewing an updated design of that interface with the community. During the research, it was determined that users would like to change the time without having to shutdown the server. It was discussed at length in slack and in the mail list and determined that was possible. 

My understanding is that we update the clock immediately, but that is an implementation detail that the backend would have to verify.

**Comment by ryanarnell** [comment]
We have updated the prototype removing the timezone from the date and time settings page. The timezone was creating confusion here when users were trying to set the time to manual.

We placed it in profile settings page. This will be a global setting where users will choose how they want to view the time stamps throughout the app.

 For example, If they select to change the timezone to their local time, the events logs timestamp will be in local time.

[View the Invision prototype](https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319476558_01-Date-And-Time-Settings-05)

![02-date-and-time-settings-05@2x](https://user-images.githubusercontent.com/4976631/77483187-8ee4dd00-6df5-11ea-9e05-c88f2b8af3a5.png)

![05-date-and-time-settings-05@2x](https://user-images.githubusercontent.com/4976631/77483252-b340b980-6df5-11ea-9ed9-d8dece7f1971.png)

![08-date-and-time-settings-03@2x](https://user-images.githubusercontent.com/4976631/77483294-d53a3c00-6df5-11ea-8e19-a4f13ec4180f.png)

**Comment by ryanarnell** [comment]
## Date and Time - Iteration 4

We have made few minor changes in this iteration.
- We redesigned the current date and time section rearranging the timezone portion and added a link to profile settings page to make it more user friendly. 
- We changed the timezone dropdown to be radio selections as there are only two options. We are also trying to eliminate users expectation of seeing all the timezones by displaying both available options upfront. 

Also adding a screenshot of the event log page showing how this will take effect there. 

[View the Invision prototype](https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319488036_01-Date-And-Time-Settings-07)

![01-date-and-time-settings-07@2x](https://user-images.githubusercontent.com/4976631/78185237-5b770380-7430-11ea-909b-83cb32a96525.png)


![02-date-and-time-settings-07@2x](https://user-images.githubusercontent.com/4976631/78185265-66319880-7430-11ea-8495-b306f2a828fc.png)


![06-date-and-time-settings-07@2x](https://user-images.githubusercontent.com/4976631/78185288-6df13d00-7430-11ea-8c68-090094450db4.png)
