### ISSUE TITLE
Loading webui-vue from the BMC causes content-security-policy errors

### ISSUE THREAD

**Issue by edtanous** [openbmc/webui-vue#32]
**Describe the bug**

When launched from the bmc, webui-vue causes 16 content-security-policy errors. In comparison, phosphor-webui very explicitly causes zero.  This shows a lack of security posture, and is likely a deterrent to those wanting to make the switch, given that security tends to be very important, and some implementations may have enabled CSP reporting, so opening webui-vue would cause a CSP security alarm on every launch.

**To Reproduce**
1. Add webui-vue to your build in local.conf, and remove phosphor-webui
2. Launch webui from a system, open debug console
3. Observe 
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-mETcdtUEPMeE1brXb0zZ2IZp4XT3Cf5gCGsi8i5CAfM='), or a nonce ('nonce-...') is required to enable inline execution.

**Expected behavior**
No errors to be present, as they're intended to show a possible attack vector.

**Screenshots**
![image](https://user-images.githubusercontent.com/599897/91228563-48194d00-e6dd-11ea-949c-e314507a7f5c.png)

**Desktop **
 - OS: Windows 10
 - Browser Chrome
 - Version Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by derick-montague** [comment]
Thanks, @edtanous - This was discovered and I have been planning to resolve this for past few weeks.

**Comment by derick-montague** [comment]
I have been looking into this and doing some Vue research. It is expected that using Vue's runtime-only build should make the application CSP compliant. I will be looking a little more into this this week.

**Comment by derick-montague** [comment]
Review: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34697

**Comment by edtanous** [comment]
Just pulled down the latest and verified.  This does indeed seem solved.  Great work!
