### ISSUE TITLE
DHCP - Network settings

### ISSUE THREAD

**Issue by yoshiemuranaka** [openbmc/webui-vue#36]
Angular app had a DHCP setting on the Network settings page. Will need to add this to webui-vue

**Comment by matijas-1987** [comment]
@derick-montague, please assign to me

**Comment by derick-montague** [comment]
Thank you, @matijas-1987!

**Comment by mmagdzix** [comment]
@matijas-1987 Can I do this feature?

**Comment by matijas-1987** [comment]
@mmagdzix ok.  @derick-montague , can you reassign this issue?

**Comment by derick-montague** [comment]
@dixsie is putting together the design info for you. All this needs is a radio button to determine if the settings will use DHCP or Static.

**Comment by derick-montague** [comment]
@mmagdzix have you been added to an organization's CLA? https://github.com/openbmc/docs/blob/master/CONTRIBUTING.md#submitting-changes-via-gerrit-server-to-openbmc

**Comment by mmagdzix** [comment]
@derick-montague James has added me to CLA

**Comment by dixsie** [comment]
@mmagdzix 
 
## Overview
- [ ] Add ability to configure Network Settings to use `Static` or `DHCP` addresses

## UX Flow / Interaction Requirements
- [ ] Add radio buttons for `Static` and `DHCP`
- [ ] Add `DHCP` table to display `IPv4Addresses` addresses with DHCP `IPv4AddressOrigin`
- [ ] Then there are no DHCP addresses, table empty-text displays `$t('global.table.emptyMessage')`
- [ ] DHCP table should always be readonly, with the delete action and trash icon button disabled
- [ ] When DHCP radio is selected, the Static IPV4 table is readonly with the delete action and trash icon button disabled


## Mockup
![Screenshot_2020-10-02 Network settings(7)](https://user-images.githubusercontent.com/26472611/94947527-65db8e00-04a3-11eb-9bb0-53680292abc1.png)
![Screenshot_2020-10-02 Network settings(6)](https://user-images.githubusercontent.com/26472611/94947529-670cbb00-04a3-11eb-939c-63d46aa564b2.png)


## cURL Commands
```
export bmc=<add IP address>

// Get token
export token=`curl -k -H "Content-Type: application/json" -X POST https://${bmc}/login -d '{"username" :  "root", "password" :  "0penBmc"}' | grep token | awk '{print $2;}' | tr -d '"'`

// Get info for the first interface
curl -k -H "X-Auth-Token: $token" https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

// Enable/disable DHCP
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"DHCPv4": {"DHCPEnabled": true}}'  
```

## Notes
- [ ] There may not be any DHCP addresses available
- [ ] https://redfish.dmtf.org/schemas/v1/IPAddresses.v1_0_10.json#/definitions/IPv4Address

**Comment by derick-montague** [comment]
@mmagdzix - Has there been any progress on this story? Do you need anything from the IBM design team?

**Comment by mmagdzix** [comment]
Hi @derick-montague, 

Unfortunately our team have higher priorities on issues related to Intel specific version and we need to focus that tasks. When we will handle them we will gladly return to community issues. I'm sorry for all the inconveniences if you need please unassign it from me.

**Comment by derick-montague** [comment]
Hi @mmagdzix - Thank you. If you haven't put any effort into this, I will remove you and move it back to ready. We may take it up in an upcoming sprint.

**Comment by derick-montague** [comment]
@dixsie has asked to work on this story.

**Comment by derick-montague** [comment]
Work completed in https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39686

**Comment by bnagaiah** [comment]
In the latest source this feature is missing. There is no radio button available for DHCP
