### ISSUE TITLE
Configuration shows up twice on the left side bar.

### ISSUE THREAD

**Issue by BMC-Bruce** [openbmc/webui-vue#39]
Configuration shows up twice on the left side bar.
Both the Gear and the Key are labeled Configuration.

Log in to the OpenBMC webui-view
Look at the left side bar and see the defect on of the last 2 items.

The gear should say Configuration as it does.
The key should not say Configuration but should say Access control

 - OS: Windows 10 
 - Browser: Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Comment by yoshiemuranaka** [comment]
Thanks @BMC-Bruce, should be fixed with https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36848

**Comment by BMC-Bruce** [comment]
Thank you @yoshiemuranaka 
https://github.com/openbmc/webui-vue/commit/4c7c5af894fdc5db46cda1a02e37777dfd0831e5
resolves the issue.

**Comment by BMC-Bruce** [comment]
The left sidebar on the Web UI now properly displays the gear with Configuration and the key with Access control.
