### ISSUE TITLE
Client Sessions

### ISSUE THREAD

**Issue by priyanka-pillai97** [openbmc/webui-vue#46]
## Use Case
---
As a **BMC admin**, I will need to be able to see which **management consoles** and **users** are connected to my BMC and remove them if needed. 

### Design Review Workflow
---
1. Each design iteration will have a comment section
2. The section will include:
    * A title with the iteration number
    * Any description or specific feedback the designer is requesting
    * Screenshots of the workflow
3. Based on community and user feedback, we create a comment for the new iteration and repeat these steps

**Comment by priyanka-pillai97** [comment]
**Main screen - View connected management consoles + associated IP addresses.** 
![Landing](https://user-images.githubusercontent.com/61419618/100880903-54c6f180-34d3-11eb-8aff-3edf44cd1242.jpg)
----
**Removing all connections from the system** 
![SelectAll](https://user-images.githubusercontent.com/61419618/100880912-57294b80-34d3-11eb-89b2-5abd40284653.jpg)
![ConfirmationModal](https://user-images.githubusercontent.com/61419618/100880933-5db7c300-34d3-11eb-8f3e-ceaab4e9506b.jpg)
![EmptyTable](https://user-images.githubusercontent.com/61419618/100880942-5ee8f000-34d3-11eb-8b33-499f9799eb60.jpg)
-----

**Removing a connection using the action button** 
![SingleButtonRemoval](https://user-images.githubusercontent.com/61419618/100881048-7cb65500-34d3-11eb-9b5c-2f51459685a1.jpg)
![WarnnigModal](https://user-images.githubusercontent.com/61419618/100881057-7e801880-34d3-11eb-8a26-3ff9578c98d6.jpg)

**Comment by priyanka-pillai97** [comment]
### Questions
1. What is the maximum number of connections that you might see here? 
2. To make a system non-HMC managed, we require a Hypervisor Reset. Is it the same for you? Are there any more steps required?

**Comment by priyanka-pillai97** [comment]
### **Updated the workflow to make the following changes:** 
**_Remove connection_ action button changed to _Disconnect_** 
![CommunityReview_Mainsccreen](https://user-images.githubusercontent.com/61419618/101624296-c2c56880-3a3f-11eb-8b92-e6225a1cfc64.jpg)

**Modals: Same modal will be shown for both management consoles as well as users when they’re being disconnected**
![CommunityReview_Modal](https://user-images.githubusercontent.com/61419618/101624328-d07aee00-3a3f-11eb-8a31-0694a755d64c.jpg)

**Comment by priyanka-pillai97** [comment]
### Questions for the community- 
1. In the case of an HMC, once it is disconnected from here, it cannot reconnect on its own. **Is that the case for other management consoles as well?**

**Comment by williamspatrick** [comment]
> ### Questions for the community-
> 1. In the case of an HMC, once it is disconnected from here, it cannot reconnect on its own. **Is that the case for other management consoles as well?**

Probably not, but that depends on how the management console saves the credentials it uses to log in.  Password and certificate based authentication would allow the MC to continue to log in; token based authentication might not, because the password would need to be re-entered to get a new token.

**Comment by ParishrutB** [comment]
> Probably not, but that depends on how the management console saves the credentials it uses to log in. Password and certificate based authentication would allow the MC to continue to log in; token based authentication might not, because the password would need to be re-entered to get a new token.

Does this mean that BMC has no control over an MC's ability to reconnect?

**Comment by williamspatrick** [comment]
> Does this mean that BMC has no control over an MC's ability to reconnect?

How would it?

Again, it depends on how you are managing credentials to the MC. If it is just an application that a user enters their user/password into and it stores, unless that password becomes invalid the application can simply log back in.

My recollection of the old HMC implementation is that as part of the initial connection, the HMC and FSP exchange some sort of certificate/token which the HMC uses for future authentication and so the FSP can invalidate that token.
