### ISSUE TITLE
Security Settings

### ISSUE THREAD

**Issue by derick-montague** [openbmc/webui-vue#5]
## Use Case
As an admin, when adding or removing a machine in my lab, I need to be able to enable or disable certain protocols for security purposes. This cannot be done via CLI or HMC.

## Invision Prototype Guidance
The Invision prototypes have hot spots allowing the reviewer to step through the workflow. To navigate a prototype, you can:

1. Click on the page and the hotspots will be revealed in blue
1. Use the arrow-right and arrow-left keys on your keyboard

## Design Review Workflow
1. Each design iteration will have a comment section
1. The section will include:
    - A title with the iteration number
    - Any description or specific feedback the designer is requesting
    - Screenshots of the workflow
1. Based on community and user feedback, we create a comment for the new iteration and repeat these steps

**Comment by ryanarnell** [comment]
## Security Settings - Iteration 0 
The low fi design we stated with to understand our use case and user needs 

![04-Security-settings-00@2x ](https://user-images.githubusercontent.com/4976631/77699953-4fe39280-6f81-11ea-88ff-8eef566bc564.png)

**Comment by ryanarnell** [comment]
## Security Settings - Iteration 1
We found out a little more information on what each sections would be and added those. Also we explored the single column option. 


![04-Security-settings-01@2x](https://user-images.githubusercontent.com/4976631/78186315-2966a100-7432-11ea-927c-88a9b6489271.png)

**Comment by ryanarnell** [comment]
## Security Settings - Iteration 2
We added the info icons to put the definition information in there and kept the description area for how that particular setting will behave. 
We also explored a radio button option but we quickly noticed that is not feasible for changing multiple items in such a form. 

![01-Security-settings-02@2x](https://user-images.githubusercontent.com/4976631/78186930-2c15c600-7433-11ea-944d-7d74d98b29ca.png)


![03-Security-settings-02@2x](https://user-images.githubusercontent.com/4976631/78187078-6aab8080-7433-11ea-949e-95e55b991f21.png)


![04-Security-settings-02@2x ](https://user-images.githubusercontent.com/4976631/78187092-70a16180-7433-11ea-88fd-3b908fbd0510.png)

**Comment by ryanarnell** [comment]
## Security Settings - Iteration 3

We updated the workflow so that the warning message is a modal and more noticeable. Also we are working on the definition of each items so that they are understood easily. 

[View the Invision prototype](https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319489310_01-Security-Settings-03)

![01-Security-settings-03@2x](https://user-images.githubusercontent.com/4976631/78305677-27badd00-7507-11ea-8cf1-32e5067e61cc.png)


![02-Security-settings-03@2x](https://user-images.githubusercontent.com/4976631/78305690-30abae80-7507-11ea-9a90-25933e3a1a58.png)


![03-Security-settings-03@2x](https://user-images.githubusercontent.com/4976631/78305701-36a18f80-7507-11ea-8dd8-e90d2d0c3ece.png)

**Comment by priyanka-pillai97** [comment]
### Security Settings - Iteration 3
---
We updated the workflow so that the description of each setting is not hidden and is understood easily.
![Security Settings](https://user-images.githubusercontent.com/61419618/100585674-f1db2c00-3313-11eb-9727-65736df513c6.jpg)

**Comment by amboar** [comment]
Hello, I have some feedback, mainly on the descriptions. As for the UI, it looks nice!

> **SSH Port 22 (BMC Shell)**

Can we just change this to "**SSH (BMC Shell Acccess)**? I think we should try to keep a consistent target of understanding. Someone who knows what Port 22 is doesn't need a "(BMC Shell)" explainer, and someone who needs the "(BMC Shell)" explainer might not grasp "Port 22". I feel this is solved by dropping "Port 22".

> SSH access to the BMC's command shell. Disabling this will disable users ability to connect to the BMC shell via SSH

This feels repetitive to me. The second sentence isn't giving the reader any more information than what they've already obtained from the first and what they can infer from the context. How about this for the complete description: "Allow users access to shell sessions on the BMC via SSH"

> **Network IPMI (Out-of-band IPMI)**
> BMC's access to out-of-band IPMI interface. Disabling this will disable users or applications ability to connect to the BMC's out-of-band IPMI.

Again this feels a little repetitive and perhaps shows some misunderstanding. Where it feels like there's a misunderstanding is it's not the BMC that accesses out-of-band IPMI, it's the user of the the BMC. So I think it would be useful to reference common tools that are affected by disabling the capability, for instance: "Allow remote users to manage the platform via IPMI, for example, using `ipmitool`".

> **RTAD**
> This option enables or disables the Remote Trusted Attestation Daemon for host firmware

I like this description. I didn't know what the "RTAD" acronym was and the description explained it to me. I think we can clean up the "This option enables or disables" bit though: "Enable remote attestation of host firmware via the Remote Trusted Attestation Daemon".

> **SSH Port 2200 (SoL)**

I think the title here hides the important information, and again like the shell session SSH configuration I talked about above, it mixes targets of understanding. My preference is that this option be titled "**Serial-over-LAN**". Removing the port number also removes the problem of one BMC catering to multiple hosts or host consoles, where we start using ports 2201, 2202 etc. I expect disabling this option to disable *all* of the Serial-over-LAN interfaces.

> SSH access to the BMC's serial over LAN. Disabling this will disable users ability to connect to the BMC SoL via SSH.

Again, I feel like this is a bit repetitive. In the context of my suggested change to the heading, I think the description could look like: "Allow access to host serial consoles over the network. Consoles are accessed by using SSH to connect to ports starting from 2200 on the BMC."

> Physical

I think this should be "Physical Interfaces" as it's more descriptive, and it would align with "Network Interfaces".

> **BMC-attached USB**
> BMC's ability to respond to device plugged into its physically attached USB

Here's my attempt at the description: "Allow use of physical USB devices on ports attached to the BMC."

Overall though, I like the UI in iteration 4, it looks clean and makes it obvious what to do at a glance.

**Comment by ParishrutB** [comment]
### Security Settings - Iteration 4.1

**Key update:** We have _reviewed and updated the copy_ based on @amboar's feedback. 

![image](https://user-images.githubusercontent.com/61419136/103525267-efd13380-4ea4-11eb-84e0-bef8e8f5ecc0.png)
