### ISSUE TITLE
Hardware Inventory and Status (VPD, FRUs and LEDs)

### ISSUE THREAD

**Issue by ParishrutB** [openbmc/webui-vue#54]
## Use Case

- As a PE/SSR, I need to be able to perform detailed analysis related to a hardware fault, so that I can point out which hardware components need to be serviced/replaced.
- As an SSR, I need to reference detailed information about one or more components, where they are installed, and switch on required LED indicators before carrying out a replacement.

## Invision Prototype Guidance
The Invision prototypes have hot spots allowing the reviewer to step through the workflow. To navigate a prototype, you can:

1. Click on the page and the hotspots will be revealed in blue
1. Use the arrow-right and arrow-left keys on your keyboard

## Design Review Workflow
1. Each design iteration will have a comment section
1. The section will include:
    - A title with the iteration number
    - Any description or specific feedback the designer is requesting
    - Screenshots of the workflow
1. Based on community and user feedback, we create a comment for the new iteration and repeat these steps

**Comment by ParishrutB** [comment]
### Iteration 1 - LoFi Mockup for testing

Hi everyone!

We are starting the design for Hardware VPD, FRUs, and LEDs. 



### Glossary
_______________

**VPD** means **Vital Product Data**, such as the serial numbers or model numbers of components. 
**FRU** means **Field Replaceable Unit**, or in other words, the hardware components which can be serviced in the field.



### Research
_______________

From our research with internal users, we learned that the following information/functions should be accessible on a single page:

**1. Hardware inventory and vital product data**
This page in IBM's GUI shows details of all the hardware components installed in the system, and their details such as part numbers, serial numbers, etc. 

![asdfadfasdfasdf](https://user-images.githubusercontent.com/61419136/109166855-28a1d080-77a3-11eb-99f3-7188100374d2.png)


**2. Concurrently maintainable FRUs**
These pages in IBM's GUI have functions to 'Remove' and 'Install' a concurrently maintainable hardware component, such as batteries and DVD drives.

![box-imagesdfdf](https://user-images.githubusercontent.com/61419136/109166886-2fc8de80-77a3-11eb-8f83-05580cc20aeb.png)


**3. Indicator LEDs**
These pages in IBM's GUI let the user switch on LED Indicators corresponding to different hardware components so that they can be clearly identified in the field.

![fadfasdf](https://user-images.githubusercontent.com/61419136/109166966-4707cc00-77a3-11eb-9c8d-48f5fffbf5b2.png)


**4. Program vital product data**
This page in IBM's GUI is useful to re-enter the system details in case they are lost due to a major error or hardware change

![aw34w3](https://user-images.githubusercontent.com/61419136/109167003-4f600700-77a3-11eb-8027-d33033d4541a.jpg)



### Test mockup:
____________

We are currently **planning to test an early, LoFi design** with a few users. Here are the **key design features:**

1. Vital system details on the top of the page.
2. Every component type has its own table, e.g. a DIMMs table, a Fans table, etc. 
3. Every component table has functions and details necessary for diagnosis and service, such as serial numbers, LED indicator switches, etc.
4. A quick links section, so that users can navigate directly and quickly to the required component table.

![HW-Landing](https://user-images.githubusercontent.com/61419136/109167092-67378b00-77a3-11eb-8c23-1183a087d251.png)

**Comment by ParishrutB** [comment]
### Iteration 1 - LoFi mockup for user testing
____________

We are currently **planning to test an early, LoFi design** with a few users. Here are the **key design features:**

1. Vital system details on the top of the page.
2. Every component type has its own table, e.g. a DIMMs table, a Fans table, etc. 
3. Every component table has functions and details necessary for diagnosis and service, such as serial numbers, LED indicator switches, etc.
4. A quick links section, so that users can navigate directly and quickly to the required component table.

![HW-Landing](https://user-images.githubusercontent.com/61419136/109167092-67378b00-77a3-11eb-8c23-1183a087d251.png)

**Comment by ParishrutB** [comment]
### Questions:
____________

1. Are these features useful to the community as well? If not, can you point out which ones are not useful or specific to your organization?
2. Any feedback/advice based on your past usage or experience with this page?

**Comment by derick-montague** [comment]
There will be some new mockups posted in the near future.
