### ISSUE TITLE
Firmware: Remove .tar references

### ISSUE THREAD

**Issue by derick-montague** [openbmc/webui-vue#55]
**Is your feature request related to a problem? Please describe.**
Not all organizations will limit the file types of firmware that can be uploaded to .tar files.

**Describe the solution you'd like**
- Remove the accept prop in the file upload component on the firmware page: https://github.com/openbmc/webui-vue/blob/b0fadef1f96df99ff5eb0637527f04bc793c8d6e/src/views/Configuration/Firmware/FirmwareFormUpdate.vue#L29

- Remove the helper text that indicates to the user to upload a .tar file
![image](https://user-images.githubusercontent.com/1183515/111576582-c2dfad80-877e-11eb-924c-aae68a49d3e0.png)
Remove: https://github.com/openbmc/webui-vue/blob/b0fadef1f96df99ff5eb0637527f04bc793c8d6e/src/views/Configuration/Firmware/FirmwareFormUpdate.vue#L24-L26
Remove: https://github.com/openbmc/webui-vue/blob/b0fadef1f96df99ff5eb0637527f04bc793c8d6e/src/locales/en-US.json#L325

**Additional context**
This was an agreed upon course of action at the GUI Design Work Group on 3/17/21.

**Comment by mmagdzix** [comment]
@derick-montague Please assign this issue to me, thx.

**Comment by derick-montague** [comment]
When you are done, if you could add the URL of this story in your Gerrit commit, that would be great!

**Comment by mmagdzix** [comment]
No problem, sorry for delay but I was whole week on sick leave.

**Comment by derick-montague** [comment]
> No problem, sorry for delay but I was whole week on sick leave.

I am sorry to hear that and hope you are feeling better! I was not trying to push. I was just making a suggestion. :)

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/42455
