### ISSUE TITLE
Display NIC status in Network settings tab

### ISSUE THREAD

**Issue by mmagdzix** [openbmc/webui-vue#59]
EWS should display the NIC link status be either up or down, and link speed for up.

Cannot find any alternative solution.

We want to display following information already provided redfish:

![nic_screeshot](https://user-images.githubusercontent.com/71821504/115551307-25aaf400-a2ab-11eb-9d04-c6bcee34d67c.png)

If this issue will be approved please assign it to me.

**Comment by derick-montague** [comment]
Added to the agenda for the May 12th, Work Group meeting. We are planning some design changes to this page and will include this information.

**Comment by derick-montague** [comment]
We discussed this today in the community work group. I will post the first design iteration here later today for further discussion.

**Comment by derick-montague** [comment]
## Design proposal v1
![image](https://user-images.githubusercontent.com/1183515/124852698-4dd0f780-df6a-11eb-936e-b28f882465ff.png)

**Comment by derick-montague** [comment]
At today's GUI Design Work Group we reviewed a new version of this design and have the following needs prior to the next review:

- Do we need to show and edit FQDN. We have not in the past.
- Need a way to show all DHCP info including default gateway. The goal was to use the IPv4 table for all addresses, but that has some limitations regarding showing the default gateway
- We will use this story for all network setting discussion, not just the static property values we need to show.

**Comment by derick-montague** [comment]
## Design Proposal v2

### Invision mock up
https://ibm.invisionapp.com/share/V5O1KG1HPT4

### Screen captures

![Network Settings - Eth0 - DHCP on](https://user-images.githubusercontent.com/1183515/135257396-26fb8c07-9530-4777-bdff-f511db20343d.png)

![Network Settings - Eth0 - DHCP Off](https://user-images.githubusercontent.com/1183515/135257399-52d2b053-50f2-4418-aaf1-2573f83e284e.png)

**Comment by derick-montague** [comment]
This was discussed in the GUI Design Work Group today and was accepted as the path forward.

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/48197/14
