### ISSUE TITLE
In-page "Refresh" button doesn't update sensor readings

### ISSUE THREAD

**Issue by zevweiss** [openbmc/webui-vue#60]
**Describe the bug**
Pressing the "Refresh" button in the upper-right corner of the page displays a progress bar animation and makes a few HTTP requests, but doesn't update the "Current value" readings displayed in the page.

**To Reproduce**
1. Go to Health -> Sensors
2. Allow sensors to load
3. Trigger some known change in sensor readings (e.g. increased temps/fan speeds with host CPU load)
4. Press the "Refresh" button in the upper right corner of the page
5. Wait for progress bar at top of page to complete and disappear
6. Observe unchanged sensor readings

**Expected behavior**
"Current value" readings (or any others that may have changed server-side) should update when "Refresh" is pressed.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu, Void)
 - Browser: Firefox
 - Version: 88

**Additional context**
A full (browser-level) refresh updates the sensor readings as expected.

**Comment by CarrieQi** [comment]
This problem can be solved by modifying  
`setSensors: (state, sensors) => {
      state.sensors = uniqBy([...state.sensors, ...sensors], 'name');
    },`
 to 
`state.sensors = uniqBy([...sensors, ...state.sensors], 'name');
`
in SensorStore.js file
