### ISSUE TITLE
Unexpected hard-coded chassis ID

### ISSUE THREAD

**Issue by leiyu-bytedance** [openbmc/webui-vue#68]
The URL related to chassis is hard-coded in the webui-vue:
```bash
src/store/modules/Control/PowerControlStore.js:        .get('/redfish/v1/Chassis/chassis/Power')
src/store/modules/Control/PowerControlStore.js:        .patch('/redfish/v1/Chassis/chassis/Power', data)
src/store/modules/Health/FanStore.js:        .get('/redfish/v1/Chassis/chassis/Thermal')
```

This is unexpected, because the `chassis` part is not hard-coded, but reflects the chassis name defined in entity-manager json.
E.g. on g220a system, the chassis URL is `/redfish/v1/Chassis/G220A`
```bash
$ curl -k -H "X-Auth-Token: $token" https://${bmc}/redfish/v1/Chassis
{
  "@odata.id": "/redfish/v1/Chassis",
  "@odata.type": "#ChassisCollection.ChassisCollection",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Chassis/G220A"
    }
  ],
  "Members@odata.count": 1,
  "Name": "Chassis Collection"
}
```

The webui code should retrieve the URI from the `@odata.id` part in `/redfish/v1/Chassis`'s response, and use the correct URL in the above js files.

**Comment by edtanous** [comment]
Duplicate/more specific case of: https://github.com/openbmc/webui-vue/issues/43

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/44850
