### ISSUE TITLE
hostname can't be modified in DHCP mode from Network settings page

### ISSUE THREAD

**Issue by habeebmohammed** [openbmc/webui-vue#70]
**Describe the bug**
In DHCP mode, Hostname alone can't be updated from WebUI. Default gateway field is required too. 
In DHCP mode default gateway should be grayed out.

**To Reproduce**
1. Go to 'overview - Networksettings page'
2. Click on hostname and modify the value.
3. Scroll down to 'save settings'
4. See error "field required" for the Default gateway.
    Hostname alone can't be updated from WebUI.

**Expected behavior**
In DHCP mode, the default gateway field should be grayed out. No value is to be entered for the default gateway.
hostname should be updated correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/23106419/126220332-372b2f4f-0597-4d35-9e5e-3faed55028af.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser - chrome

**Comment by dixsie** [comment]
I'm not sure why gateway should be disabled if DHCP is enabled. Users are still able to add static ipv4 addresses even when dhcp is enabled. The way the Redfish response is structured, the gateway is saved as a property associated with each static ipv4 address (which is always editable). 

- Why shouldn't users be allowed to edit gateway when DHCP is enabled?
- Is the form structure confusing or do you think this is a bug?

FYI: The design of this page is currently being updated by @derick-montague. Please feel free to join us at our next [design workgroup meeting](https://github.com/openbmc/openbmc/wiki/GUI-Design-work-group) to discuss this further, or we can continue on Github.

**Comment by derick-montague** [comment]
I think the issue here is that the hostname can't be saved due to the Default gateway being a required field. I don't know why default gateway is  required at all. If the default gateway is null, it should default to 0.0.0.0. I expect to happen on the backend. If that is not true, we will need to make sure to send that value if the field is left empty. I don't think it should be a required field.

Is that an  accurate description of the issue @habeebmohammed?

**Comment by habeebmohammed** [comment]
> I think the issue here is that the hostname can't be saved due to the Default gateway being a required field. I don't know why default gateway is required at all. If the default gateway is null, it should default to 0.0.0.0. I expect to happen on the backend. If that is not true, we will need to make sure to send that value if the field is left empty. I don't think it should be a required field.
> 
> Is that an accurate description of the issue @habeebmohammed?

Yes, That is correct. Hostname alone should be able to set.

**Comment by dixsie** [comment]
Thanks for clarifying! 🙂 I'll update and make the change.

**Comment by dixsie** [comment]
Work for this issue will be completed with the network settings page redesign. Conversation for the redesign can be found here https://github.com/openbmc/webui-vue/issues/59#issuecomment-876071256

**Comment by jmbills** [comment]
It looks like this was fixed in the redesign.  I am able to update my BMC hostname from the new Network Settings page while in DHCP mode.

**Comment by derick-montague** [comment]
I love it when a plan comes together!
