### ISSUE TITLE
Different UI elements don't have translation

### ISSUE THREAD

**Issue by Kostr** [openbmc/webui-vue#76]
I've synchronized `ru-RU.json` translation file with the `en-US.json` file, but still I see that some UI elements lack translation.

Here is a summary of the issues that I've found on my system:

Sensors page (hardware-status/sensors):
![2021-09-03_15-20-14](https://user-images.githubusercontent.com/2064127/132005428-00cc20bf-95f5-42d8-b974-a2274950f7d8.png)

Server power operations (operations/server-power-operations):
![xxx](https://user-images.githubusercontent.com/2064127/132005545-edb5035e-4c53-403d-b305-43548ea27cf8.png)

Power restore policy (settings/power-restore-policy):
![2021-09-03_15-26-08](https://user-images.githubusercontent.com/2064127/132005614-67994ccd-82fd-4fc6-bb66-1f398141b852.png)

User management (security-and-access/user-management):
![2021-09-03_15-27-52 (2)](https://user-images.githubusercontent.com/2064127/132005797-07ba9283-73f0-4010-b355-12cbe2041c99.png)

Inventory and LEDs (hardware-status/inventory):
![2021-09-03_15-31-24](https://user-images.githubusercontent.com/2064127/132005814-8a442b60-af9c-4cf7-a701-9c600f24b21e.png)
![2021-09-03_15-32-32](https://user-images.githubusercontent.com/2064127/132005821-b7ffaa8e-5dd6-49fe-bcc3-4dad0a059422.png)

**Comment by derick-montague** [comment]
Closing based on [comments in Discord](https://discord.com/channels/775381525260664832/776550056391606352/883330629209571328)

**Comment by gtmills** [comment]
I don't think these are in yet. Reopened.

**Comment by dixsie** [comment]
@gtmills this was closed because these strings are generated dynamically from Redfish and that is why they aren't translated on the front-end. I think the "privilege" label on Local User management can be translated.

**Comment by Kostr** [comment]
Thanks for the explanation.
But isn't there a possibility to include these Redfish enum properties in the translation?
Because having whole sentences like `The system always remains powered off when power is applied` makes a translation look incomplete.

**Comment by derick-montague** [comment]
> But isn't there a possibility to include these Redfish enum properties in the translation?

We discussed this at one point and it was suggested that we would provide translation server-side. We expected that we could send the language as a parameter and the values in the response would be returned translated. Whether that is realistic or not, I'm not sure. I do think that there could be some mapping of terms like enabled and disabled or boolean values. 

If that was the decision, any changes to the Redfish API could result in the i18n variable name  being displayed if the mapping was not found. If someone wants to pursue this, I have marked this as `help wanted`.

**Comment by williamspatrick** [comment]
> We discussed this at one point and it was suggested that we would provide translation server-side. We expected that we could send the language as a parameter and the values in the response would be returned translated. 

It isn’t obvious to me that this would be valid by the Redfish spec, but there are some words in the spec that I don’t fully grasp.

> Property names, parameter names, and enumeration values in the JSON response payload are never localized but translated copies of those names may be provided as additional annotations in the localized schema for use by client applications.

https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.13.0.pdf

I think this is saying that we would have to provide alternative copies of the schema in various languages and on the client-side the application would need to take the English enumeration value and look it up in the localized schema.  The spec also continues:

> Schemas and registries in non-English languages shall use the appropriate schema annotations to identify their language. Descriptive property, parameter, and enumeration text not translated into the specified language shall be removed from localized versions. This removal enables software and tools to combine normative and localized copies, especially for minor schema version differences.

I think this is implying that we either need these translated schemas or we leave various values for them blank and the application (the webui) fills in its local copies of the translation.  Either way, it seems to be on the webui to do the translation of the Redfish JSON response either using a localized schema provided by the Redfish Server or using its own localization information.

**Comment by dixsie** [comment]
Discussed at the community [GUI design work group](https://github.com/openbmc/openbmc/wiki/GUI-Design-work-group) today.

**Comment by williamspatrick** [comment]
> Discussed at the community [GUI design work group](https://github.com/openbmc/openbmc/wiki/GUI-Design-work-group) today.

Are there minutes from that discussion that didn't end up in the linked-to wiki entry?

**Comment by kirankumarb07** [comment]
Commit Link : https://github.com/openbmc/webui-vue/commit/3bf966a73eb55dbc0751734ce5bd78105e2d1c70

Gerrit PR Link : https://gerrit.openbmc.org/c/openbmc/webui-vue/+/60723

**Comment by Kostr** [comment]
Thanks! I've checked it, the issue is solved now
