### ISSUE TITLE
Add a section to update session timeout

### ISSUE THREAD

**Issue by johnlliiuu** [openbmc/webui-vue#79]
Redfish has the ability to configure session timeout. Is it possible to add a configure section in web UI? Below is what my design page looks like.
![timeout_setting](https://user-images.githubusercontent.com/85477545/133749671-abad9125-39d9-4554-a4bb-e84ae2129c08.PNG)

**Comment by kirankumarb07** [comment]
Please capture this feature enhancement as like below under **Security and access -> Policies page.**  



![image](https://user-images.githubusercontent.com/89591579/223140397-125bd0b6-e48b-4eee-aeb6-6e1b1e7098d9.png)
 
![image](https://user-images.githubusercontent.com/89591579/223141060-78b1ae24-64cb-40ab-96c2-83f850ad044e.png)


@sivaprabug  @suryav9724 @dineshkumar9376

**Comment by kirankumarb07** [comment]
PR#https://gerrit.openbmc.org/c/openbmc/webui-vue/+/62005 merged hence please proceed to close this issue.
