### ISSUE TITLE
Hardware Status

### ISSUE THREAD

**Issue by ryanarnell** [openbmc/webui-vue#8]
## Use Case
As a BMC user I need to be able to know the information and  status of various hardware in the system so that I can troubleshoot easily if there is an issue. 

## Invision Prototype Guidance
The Invision prototypes have hot spots allowing the reviewer to step through the workflow. To navigate a prototype, you can:

1. Click on the page and the hotspots will be revealed in blue
1. Use the arrow-right and arrow-left keys on your keyboard

## Design Review Workflow
1. Each design iteration will have a comment section
1. The section will include:
    - A title with the iteration number
    - Any description or specific feedback the designer is requesting
    - Screenshots of the workflow
1. Based on community and user feedback, we create a comment for the new iteration and repeat these steps

**Comment by ryanarnell** [comment]
## Hardware status- Iteration 0

We are trying to understand more why users will go to this page. For this reason, we created these two low fi prototypes to test. 

[View the Invision prototype](https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319489588_01-Hardware-Status-00)

![01-hardware-status-00@2x](https://user-images.githubusercontent.com/4976631/78305325-3ce33c00-7506-11ea-9687-b16f42780f37.png)


![02-hardware-status-00@2x](https://user-images.githubusercontent.com/4976631/78305332-410f5980-7506-11ea-933b-f159aedd2f73.png)


![03-hardware-status-00@2x](https://user-images.githubusercontent.com/4976631/78305340-47053a80-7506-11ea-9f79-c299485fb248.png)


![04-hardware-status-00@2x](https://user-images.githubusercontent.com/4976631/78305350-4c628500-7506-11ea-9d71-530f8b01fd1c.png)

**Comment by lukkep** [comment]
Hey,
Small thing to Design Proposal A, when dropdown is unfolded.
Can I suggest making a light background effect like in the image attached? :)

Also the headers could be darker then.

![A_edited](https://user-images.githubusercontent.com/25308566/81723688-86b72e80-9483-11ea-8fcc-27316e412303.png)

**Comment by ryanarnell** [comment]
> Hey,
> Small thing to Design Proposal A, when dropdown is unfolded.
> Can I suggest making a light background effect like in the image attached? :)
> 
> Also the headers could be darker then.
> 
> ![A_edited](https://user-images.githubusercontent.com/25308566/81723688-86b72e80-9483-11ea-8fcc-27316e412303.png)

Thank you @lukkep  for your feedback. Yes we are working on the layout especially for the color of the detail segment and header as you mentioned. I will pass your suggestion to the team.

**Comment by ryanarnell** [comment]
## Hardware status- Iteration MVP
We wanted to reach parity with our existing OpenBMC GUI and include some update along the way. 

1. Separated the hardware component sections.
2. Added sorting to the sections columns.
3. Introduced searching and filtering for long tables like DIMMs.
4. Added health status information.
5. Exposed important information like part number and serial numbers in table header.

[View the Invision prototype](https://ibm.invisionapp.com/share/V3O02B362ZE#/screens/319550704_01-Hardware-Status-04)

### Hardware status page
![01-hardware-status-04@2x](https://user-images.githubusercontent.com/4976631/82504129-475e9280-9ac0-11ea-8d4d-7971daaf9f5e.png)


### Hardware status page expanded 
![02-hardware-status-04@2x](https://user-images.githubusercontent.com/4976631/82504138-4d547380-9ac0-11ea-8499-87e611777521.png)
