### ISSUE TITLE
Page headings don't get translated on language change until page refresh

### ISSUE THREAD

**Issue by Kostr** [openbmc/webui-vue#82]
When the language is changed everything is getting translated to the new language right away except the page headings. They stay in the old language until the page refresh.

Example:
- login with Russian
- exit to the login page
- change language to English and login
- this would result with such bug:
![2021-10-19_09-09-17](https://user-images.githubusercontent.com/2064127/137853464-e3de3f20-4384-4e08-a483-f0128b314759.png)
This error would be present on all of the pages:
![2021-10-19_09-09-52](https://user-images.githubusercontent.com/2064127/137853551-1b9f40f7-0c3b-4c4f-b20c-7010944a7dbe.png)
If the page is refreshed everything goes back to normal:
![2021-10-19_09-10-47](https://user-images.githubusercontent.com/2064127/137853679-1361e49d-b0d9-48f9-9750-0fb2b6b70d5b.png)

The same error is present in the opposite way. To test it:
- exit to login page
- change language to Russian and login
![2021-10-19_09-11-21](https://user-images.githubusercontent.com/2064127/137853771-1f94175f-e4bb-4e29-8662-ada7708fd691.png)
![2021-10-19_09-11-50](https://user-images.githubusercontent.com/2064127/137853779-da633520-3efb-4253-8a3f-b6d83e669e77.png)

**Tested on:**
 - Windows 10
 - Chrome 94.0.4606.81

**Comment by kirankumarb07** [comment]
Gerrit Link : https://gerrit.openbmc.org/c/openbmc/webui-vue/+/60721 

Commit Link : https://github.com/openbmc/webui-vue/commit/38e131ada65ea78b0e73eebde488002b3e2369c9

**Comment by Kostr** [comment]
Thanks! I've checked it, the issue is solved now
