### ISSUE TITLE
webui看过来！！！以下方法无效！！！ 您需要登录才能查看标题。通过在“BMC HOST OR BMC IP ADDRESS”字段中键入 QEMU 会话（例如 localhost:2443），将 Web UI 指向您的 QEMU 会话。

### ISSUE THREAD

**Issue by fishermess** [openbmc/webui-vue#85]
如果真的在8080端口的“BMC HOST OR BMC IP ADDRESS”字段输入127.0.0.1:2443，无效，显示Server unreachable。2443镜像已经启动！！！

**Comment by suyogchaudhary** [comment]
What is the solution for this? I am also facing the same issue.
