### ISSUE TITLE
Progress bar never disappears on the Overview page

### ISSUE THREAD

**Issue by Kostr** [openbmc/webui-vue#89]
At least on some systems (for example AMD EthanolX CRB) progress bar never disappears on the Overview page.

From some testing I've discovered that this issue is happening because of this promise:
```
    const dumpsPromise = new Promise((resolve) => {
      this.$root.$on('overview-dumps-complete', () => resolve());
    });
```
https://github.com/openbmc/webui-vue/blob/5e5b48b0a452b5b121b9221019cf7616545b188b/src/views/Overview/Overview.vue#L63 

`overview-dumps-complete` is emitted here:
```
  created() {
    this.$store.dispatch('dumps/getBmcDumps').finally(() => {
      this.$root.$emit('overview-dumps-complete');
    });
  },
```
https://github.com/openbmc/webui-vue/blob/cc79a53192de73457cb4c8c3350d896d952bb106/src/views/Overview/OverviewDumps.vue#L37

And here is `getBmcDumps` function:
```
    async getBmcDumps({ commit }) {
      return await api
        .get('/redfish/v1/Managers/bmc/LogServices/Dump/Entries')
        .then(({ data = {} }) => commit('setBmcDumps', data.Members || []))
        .catch((error) => console.log(error));
    },
```
https://github.com/openbmc/webui-vue/blob/5e5b48b0a452b5b121b9221019cf7616545b188b/src/store/modules/Logs/DumpsStore.js#L27

As you can see this function tries to access `/redfish/v1/Managers/bmc/LogServices/Dump/Entries` redfish page.
But in case of the AMD EthanolX CRB this page is not present.
`redfish/v1/Managers/bmc/LogServices` gives:
```
{
"@odata.id": "/redfish/v1/Managers/bmc/LogServices",
"@odata.type": "#LogServiceCollection.LogServiceCollection",
"Description": "Collection of LogServices for this Manager",
"Members": [],
"Members@odata.count": 0,
"Name": "Open BMC Log Services Collection"
}
```
As the dumps feature is optional this is probably a bug.

It looks like Overview has started to wait for the dumps promise after this commit https://github.com/openbmc/webui-vue/commit/6a192d526c9efebf7a614a9aa473eee62e555fc5

**Comment by dixsie** [comment]
@Kostr Some work has been pushed to resolve this bug here https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/49186

**Comment by kennyneedsmilky** [comment]
@Kostr , can you check later to see what kind of error you get when you put https://localhost:8000/redfish/v1/Managers/bmc/LogServices/Dump/Entries into the browser?

**Comment by dixsie** [comment]
@kennyneedsmilky dumps are IBM specific so this bug also includes not throwing an error when that path is not available

**Comment by kennyneedsmilky** [comment]
@dixsie @Kostr, if that is the case, then I don't see any .catch() in the Promise.all in Overview.vue . Even though it has a .finally(), if there isn't a .catch() before the .finally() . .catch() can be used to console.log the rejection, but .finally() will run its function regardless of getting a resolve or rejection. I'm not 100% sure if this is the absolute solution, but it is a giant step closer. For debugging purposes until the problem has a solid solution, one can try to put the this.endLoader() in a catch and see if that stops the loading bar while throwing in error in the console.log 

like...

`.catch((err) => {
    console.error(err);
    this.endLoader();
  })`

But, to be honest, .fianlly() should stop the loading bar since it already had the  this.endLoader() function.

**Comment by Kostr** [comment]
> @Kostr Some work has been pushed to resolve this bug here https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/49186

I've tried this patch and it doesn't resolve the issue https://github.com/openbmc/webui-vue/issues/89

> @Kostr , can you check later to see what kind of error you get when you put https://localhost:8000/redfish/v1/Managers/bmc/LogServices/Dump/Entries into the browser?

Page returns:
```
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">Not Found</pre></body></html>
```
Since
```
GET https://192.168.101.140/redfish/v1/Managers/bmc/LogServices/Dump/Entries 404 (Not Found)
```

**Comment by dixsie** [comment]
Still not resolved

**Comment by huchunliang** [comment]
mounted() {
    this.endLoader();
  },is this ok?

**Comment by kirankumarb07** [comment]
@sivaprabug @suryav9724 @dineshkumar9376

**Comment by Kostr** [comment]
It looks like this issue was fixed with the patchset `60647: Fix bug in Overview endless loading` | https://gerrit.openbmc.org/c/openbmc/webui-vue/+/60647
