### ISSUE TITLE
Web GUI doesn't redirect to login page after session timeout

### ISSUE THREAD

**Issue by stevenlee7189** [openbmc/webui-vue#91]
**Describe the bug**
After session expired, if users stay on KVM or Virtual Media page and switch pages between KVM and Virtual Media pages, web gui doesn't redirect to login page.

**To Reproduce**
1. Go to 'Operations'
2. Click on 'KVM'
3. Wait until session expired
4. Click on 'Virtual Media', gui doesn't redirect to login page.
5. Click on 'KVM', KVM staus shows Disconnected, gui doesn't redirect to login page either.

**Expected behavior**
When users access KVM/Virtual Media page after session expired, web gui should redirect to login page.

**Desktop (please complete the following information):**
 - OS: Windows 10 professional 21H1
 - Browser: Chrome
 - Version:  97.0.4692.71

**Comment by kirankumarb07** [comment]
https://gerrit.openbmc.org/c/openbmc/webui-vue/+/61398

**Comment by kirankumarb07** [comment]
Closing this task as PR#https://gerrit.openbmc.org/c/openbmc/webui-vue/+/61398 merged.

**Comment by kirankumarb07** [comment]
@stevenlee7189 Can you help to close this task as per below comment.

https://github.com/openbmc/webui-vue/issues/91#issuecomment-1488853789
