### ISSUE TITLE
Websocket does not work in development mode.

### ISSUE THREAD

**Issue by semicloud** [openbmc/webui-vue#94]
I set `BASE_URL="https://localhost:2443"` in file `.env.development.local`, then run `npm run serve`.

My question is https requests can proxy to `https://localhost:2443`, but websocket proxy failed.

I add `ws: true` to `vue.config.js` but still not work.

**Comment by fanxp-666** [comment]
Is it resolved now?

**Comment by fanxp-666** [comment]
![image](https://user-images.githubusercontent.com/104194908/212224010-c28375a7-a897-45fd-9e8d-398ccea4e065.png)
试试去掉这个header

**Comment by fishermess** [comment]
You need to set connectiong as 'upgrade' in vue.config.js rather than 'keep-alive'.
