### ISSUE TITLE
Serial console opened in new tab shows spurious "must be powered on to connect" error

### ISSUE THREAD

**Issue by zevweiss** [openbmc/webui-vue#97]
**Describe the bug**
Opening the SoL console in a new tab displays an error message saying "System must be powered on to connect" even when the system is powered on, and shows the status as "Disconnected" while the main SoL page shows "Connected".  The SoL console functions normally despite the error, but it's confusing & misleading.

**To Reproduce**
1. With the host powered on, go to the Operations -> SoL console page
2. Click on the "Open in new tab" button
3. Observe the "System must be powered on to connect error"

**Expected behavior**
No spurious error messages

**Screenshots**
![sol-console-error](https://user-images.githubusercontent.com/384597/192398295-e6a1c8c8-16fa-46f6-9251-31238f856244.png)

**Desktop (please complete the following information):**
 - OS: Linux, MacOS
 - Browser: Firefox, Chrome
 - Version: MacOS Chrome 105, MacOS Firefox 87, Linux Firefox 91

**Comment by wayne-tung** [comment]
In commit: 4dd7eabfa4476e264e051dc0178a333452a6b175

We changed the "**getServerStatus**" to "**getSystemInfo**" in GlobalStore.js

We still used old store API "**global/getServerStatus**" to get current server status in SOL page "**created**" function.

**Comment by kirankumarb07** [comment]
Gerrit Link : https://gerrit.openbmc.org/c/openbmc/webui-vue/+/60720

**Comment by zevweiss** [comment]
Thanks for the fix @kirankumarb07.
